name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        run: |
          docker-compose down
          docker-compose up -d --build frontend
