name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: |
          docker-compose down
          docker-compose up -d --build backend
